[[redirects]]
  from = "https://cryptoanalyze.netlify.com/*"
  to = "https://cryptoanalyze.app"
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"